---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-sample-controller
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sample-controller
  namespace: default

spec:
  selector:
    matchLabels:
      app: k8s-sample-controller

  template:
    metadata:
      labels:
        app: k8s-sample-controller

    spec:
      serviceAccountName: k8s-sample-controller
      containers:
        - name: controller
          image: kevinpollet/k8s-sample-controller
          imagePullPolicy: IfNotPresent
